--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

-- Started on 2025-08-18 14:22:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16384)
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- TOC entry 3382 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16449)
-- Name: devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.devices (
    id bigint NOT NULL,
    device_model character varying(255),
    device_name character varying(255),
    device_uid character varying(255) NOT NULL,
    active boolean
);


ALTER TABLE public.devices OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16448)
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16568)
-- Name: user_devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_devices (
    id bigint NOT NULL,
    assigned_name character varying(255) NOT NULL,
    device_id bigint,
    user_id integer,
    active boolean DEFAULT true,
    user_room_id bigint NOT NULL,
    status character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    CONSTRAINT chk_user_devices_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE_RESERVED'::character varying, 'RETIRED'::character varying])::text[])))
);


ALTER TABLE public.user_devices OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16567)
-- Name: user_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_devices_id_seq OWNER TO postgres;

--
-- TOC entry 3383 (class 0 OID 0)
-- Dependencies: 219
-- Name: user_devices_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_devices_id_seq OWNED BY public.user_devices.id;


--
-- TOC entry 222 (class 1259 OID 16653)
-- Name: user_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_room (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    room_name character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.user_room OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16652)
-- Name: user_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_room_id_seq OWNER TO postgres;

--
-- TOC entry 3384 (class 0 OID 0)
-- Dependencies: 221
-- Name: user_room_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_room_id_seq OWNED BY public.user_room.id;


--
-- TOC entry 216 (class 1259 OID 16438)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    active boolean
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16437)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 3385 (class 0 OID 0)
-- Dependencies: 215
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 223 (class 1259 OID 16674)
-- Name: v_available_devices; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_available_devices AS
 SELECT d.id,
    d.device_model,
    d.device_name,
    d.device_uid,
    d.active
   FROM (public.devices d
     LEFT JOIN public.user_devices ud ON (((ud.device_id = d.id) AND (ud.active = true))))
  WHERE ((d.active = true) AND (ud.id IS NULL));


ALTER TABLE public.v_available_devices OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16678)
-- Name: v_device_stock; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_device_stock AS
 SELECT d.device_model,
    count(*) AS total_units,
    sum(
        CASE
            WHEN (ud.id IS NULL) THEN 1
            ELSE 0
        END) AS available_units
   FROM (public.devices d
     LEFT JOIN public.user_devices ud ON (((ud.device_id = d.id) AND (ud.active = true))))
  WHERE (d.active = true)
  GROUP BY d.device_model;


ALTER TABLE public.v_device_stock OWNER TO postgres;

--
-- TOC entry 3198 (class 2604 OID 16571)
-- Name: user_devices id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_devices ALTER COLUMN id SET DEFAULT nextval('public.user_devices_id_seq'::regclass);


--
-- TOC entry 3201 (class 2604 OID 16656)
-- Name: user_room id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_room ALTER COLUMN id SET DEFAULT nextval('public.user_room_id_seq'::regclass);


--
-- TOC entry 3197 (class 2604 OID 16441)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3372 (class 0 OID 16449)
-- Dependencies: 218
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.devices (id, device_model, device_name, device_uid, active) FROM stdin;
1	Led-White	White LED	LEDW-000001	t
2	Led-White	White LED	LEDW-000002	t
3	Led-White	White LED	LEDW-000003	t
4	Led-White	White LED	LEDW-000004	t
5	Led-White	White LED	LEDW-000005	t
6	Led-White	White LED	LEDW-000006	t
7	Led-White	White LED	LEDW-000007	t
8	Led-White	White LED	LEDW-000008	t
9	Led-White	White LED	LEDW-000009	t
10	Led-White	White LED	LEDW-000010	t
11	Led-White	White LED	LEDW-000011	t
12	Led-White	White LED	LEDW-000012	t
13	Led-White	White LED	LEDW-000013	t
14	Led-White	White LED	LEDW-000014	t
15	Led-White	White LED	LEDW-000015	t
16	Led-White	White LED	LEDW-000016	t
17	Led-White	White LED	LEDW-000017	t
18	Led-White	White LED	LEDW-000018	t
19	Led-White	White LED	LEDW-000019	t
20	Led-White	White LED	LEDW-000020	t
21	Led-White	White LED	LEDW-000021	t
22	Led-White	White LED	LEDW-000022	t
23	Led-White	White LED	LEDW-000023	t
24	Led-White	White LED	LEDW-000024	t
25	Led-White	White LED	LEDW-000025	t
26	Led-White	White LED	LEDW-000026	t
27	Led-White	White LED	LEDW-000027	t
28	Led-White	White LED	LEDW-000028	t
29	Led-White	White LED	LEDW-000029	t
30	Led-White	White LED	LEDW-000030	t
31	Led-White	White LED	LEDW-000031	t
32	Led-White	White LED	LEDW-000032	t
33	Led-White	White LED	LEDW-000033	t
34	Led-White	White LED	LEDW-000034	t
35	Led-White	White LED	LEDW-000035	t
36	Led-White	White LED	LEDW-000036	t
37	Led-White	White LED	LEDW-000037	t
38	Led-White	White LED	LEDW-000038	t
39	Led-White	White LED	LEDW-000039	t
40	Led-White	White LED	LEDW-000040	t
41	Led-White	White LED	LEDW-000041	t
42	Led-White	White LED	LEDW-000042	t
43	Led-White	White LED	LEDW-000043	t
44	Led-White	White LED	LEDW-000044	t
45	Led-White	White LED	LEDW-000045	t
46	Led-White	White LED	LEDW-000046	t
47	Led-White	White LED	LEDW-000047	t
48	Led-White	White LED	LEDW-000048	t
49	Led-White	White LED	LEDW-000049	t
50	Led-White	White LED	LEDW-000050	t
51	Led-White	White LED	LEDW-000051	t
52	Led-White	White LED	LEDW-000052	t
53	Led-White	White LED	LEDW-000053	t
54	Led-White	White LED	LEDW-000054	t
55	Led-White	White LED	LEDW-000055	t
56	Led-White	White LED	LEDW-000056	t
57	Led-White	White LED	LEDW-000057	t
58	Led-White	White LED	LEDW-000058	t
59	Led-White	White LED	LEDW-000059	t
60	Led-White	White LED	LEDW-000060	t
61	Led-White	White LED	LEDW-000061	t
62	Led-White	White LED	LEDW-000062	t
63	Led-White	White LED	LEDW-000063	t
64	Led-White	White LED	LEDW-000064	t
65	Led-White	White LED	LEDW-000065	t
66	Led-White	White LED	LEDW-000066	t
67	Led-White	White LED	LEDW-000067	t
68	Led-White	White LED	LEDW-000068	t
69	Led-White	White LED	LEDW-000069	t
70	Led-White	White LED	LEDW-000070	t
71	Led-White	White LED	LEDW-000071	t
72	Led-White	White LED	LEDW-000072	t
73	Led-White	White LED	LEDW-000073	t
74	Led-White	White LED	LEDW-000074	t
75	Led-White	White LED	LEDW-000075	t
76	Led-White	White LED	LEDW-000076	t
77	Led-White	White LED	LEDW-000077	t
78	Led-White	White LED	LEDW-000078	t
79	Led-White	White LED	LEDW-000079	t
80	Led-White	White LED	LEDW-000080	t
81	Led-White	White LED	LEDW-000081	t
82	Led-White	White LED	LEDW-000082	t
83	Led-White	White LED	LEDW-000083	t
84	Led-White	White LED	LEDW-000084	t
85	Led-White	White LED	LEDW-000085	t
86	Led-White	White LED	LEDW-000086	t
87	Led-White	White LED	LEDW-000087	t
88	Led-White	White LED	LEDW-000088	t
89	Led-White	White LED	LEDW-000089	t
90	Led-White	White LED	LEDW-000090	t
91	Led-White	White LED	LEDW-000091	t
92	Led-White	White LED	LEDW-000092	t
93	Led-White	White LED	LEDW-000093	t
94	Led-White	White LED	LEDW-000094	t
95	Led-White	White LED	LEDW-000095	t
96	Led-White	White LED	LEDW-000096	t
97	Led-White	White LED	LEDW-000097	t
98	Led-White	White LED	LEDW-000098	t
99	Led-White	White LED	LEDW-000099	t
100	Led-White	White LED	LEDW-000100	t
101	Led-Red	Red LED	LEDR-000001	t
102	Led-Red	Red LED	LEDR-000002	t
103	Led-Red	Red LED	LEDR-000003	t
104	Led-Red	Red LED	LEDR-000004	t
105	Led-Red	Red LED	LEDR-000005	t
106	Led-Red	Red LED	LEDR-000006	t
107	Led-Red	Red LED	LEDR-000007	t
108	Led-Red	Red LED	LEDR-000008	t
109	Led-Red	Red LED	LEDR-000009	t
110	Led-Red	Red LED	LEDR-000010	t
111	Led-Red	Red LED	LEDR-000011	t
112	Led-Red	Red LED	LEDR-000012	t
113	Led-Red	Red LED	LEDR-000013	t
114	Led-Red	Red LED	LEDR-000014	t
115	Led-Red	Red LED	LEDR-000015	t
116	Led-Red	Red LED	LEDR-000016	t
117	Led-Red	Red LED	LEDR-000017	t
118	Led-Red	Red LED	LEDR-000018	t
119	Led-Red	Red LED	LEDR-000019	t
120	Led-Red	Red LED	LEDR-000020	t
121	Led-Red	Red LED	LEDR-000021	t
122	Led-Red	Red LED	LEDR-000022	t
123	Led-Red	Red LED	LEDR-000023	t
124	Led-Red	Red LED	LEDR-000024	t
125	Led-Red	Red LED	LEDR-000025	t
126	Led-Red	Red LED	LEDR-000026	t
127	Led-Red	Red LED	LEDR-000027	t
128	Led-Red	Red LED	LEDR-000028	t
129	Led-Red	Red LED	LEDR-000029	t
130	Led-Red	Red LED	LEDR-000030	t
131	Led-Red	Red LED	LEDR-000031	t
132	Led-Red	Red LED	LEDR-000032	t
133	Led-Red	Red LED	LEDR-000033	t
134	Led-Red	Red LED	LEDR-000034	t
135	Led-Red	Red LED	LEDR-000035	t
136	Led-Red	Red LED	LEDR-000036	t
137	Led-Red	Red LED	LEDR-000037	t
138	Led-Red	Red LED	LEDR-000038	t
139	Led-Red	Red LED	LEDR-000039	t
140	Led-Red	Red LED	LEDR-000040	t
141	Led-Red	Red LED	LEDR-000041	t
142	Led-Red	Red LED	LEDR-000042	t
143	Led-Red	Red LED	LEDR-000043	t
144	Led-Red	Red LED	LEDR-000044	t
145	Led-Red	Red LED	LEDR-000045	t
146	Led-Red	Red LED	LEDR-000046	t
147	Led-Red	Red LED	LEDR-000047	t
148	Led-Red	Red LED	LEDR-000048	t
149	Led-Red	Red LED	LEDR-000049	t
150	Led-Red	Red LED	LEDR-000050	t
151	Led-Red	Red LED	LEDR-000051	t
152	Led-Red	Red LED	LEDR-000052	t
153	Led-Red	Red LED	LEDR-000053	t
154	Led-Red	Red LED	LEDR-000054	t
155	Led-Red	Red LED	LEDR-000055	t
156	Led-Red	Red LED	LEDR-000056	t
157	Led-Red	Red LED	LEDR-000057	t
158	Led-Red	Red LED	LEDR-000058	t
159	Led-Red	Red LED	LEDR-000059	t
160	Led-Red	Red LED	LEDR-000060	t
161	Led-Red	Red LED	LEDR-000061	t
162	Led-Red	Red LED	LEDR-000062	t
163	Led-Red	Red LED	LEDR-000063	t
164	Led-Red	Red LED	LEDR-000064	t
165	Led-Red	Red LED	LEDR-000065	t
166	Led-Red	Red LED	LEDR-000066	t
167	Led-Red	Red LED	LEDR-000067	t
168	Led-Red	Red LED	LEDR-000068	t
169	Led-Red	Red LED	LEDR-000069	t
170	Led-Red	Red LED	LEDR-000070	t
171	Led-Red	Red LED	LEDR-000071	t
172	Led-Red	Red LED	LEDR-000072	t
173	Led-Red	Red LED	LEDR-000073	t
174	Led-Red	Red LED	LEDR-000074	t
175	Led-Red	Red LED	LEDR-000075	t
176	Led-Red	Red LED	LEDR-000076	t
177	Led-Red	Red LED	LEDR-000077	t
178	Led-Red	Red LED	LEDR-000078	t
179	Led-Red	Red LED	LEDR-000079	t
180	Led-Red	Red LED	LEDR-000080	t
181	Led-Red	Red LED	LEDR-000081	t
182	Led-Red	Red LED	LEDR-000082	t
183	Led-Red	Red LED	LEDR-000083	t
184	Led-Red	Red LED	LEDR-000084	t
185	Led-Red	Red LED	LEDR-000085	t
186	Led-Red	Red LED	LEDR-000086	t
187	Led-Red	Red LED	LEDR-000087	t
188	Led-Red	Red LED	LEDR-000088	t
189	Led-Red	Red LED	LEDR-000089	t
190	Led-Red	Red LED	LEDR-000090	t
191	Led-Red	Red LED	LEDR-000091	t
192	Led-Red	Red LED	LEDR-000092	t
193	Led-Red	Red LED	LEDR-000093	t
194	Led-Red	Red LED	LEDR-000094	t
195	Led-Red	Red LED	LEDR-000095	t
196	Led-Red	Red LED	LEDR-000096	t
197	Led-Red	Red LED	LEDR-000097	t
198	Led-Red	Red LED	LEDR-000098	t
199	Led-Red	Red LED	LEDR-000099	t
200	Led-Red	Red LED	LEDR-000100	t
201	Led-Blue	Blue LED	LEDB-000001	t
202	Led-Blue	Blue LED	LEDB-000002	t
203	Led-Blue	Blue LED	LEDB-000003	t
204	Led-Blue	Blue LED	LEDB-000004	t
205	Led-Blue	Blue LED	LEDB-000005	t
206	Led-Blue	Blue LED	LEDB-000006	t
207	Led-Blue	Blue LED	LEDB-000007	t
208	Led-Blue	Blue LED	LEDB-000008	t
209	Led-Blue	Blue LED	LEDB-000009	t
210	Led-Blue	Blue LED	LEDB-000010	t
211	Led-Blue	Blue LED	LEDB-000011	t
212	Led-Blue	Blue LED	LEDB-000012	t
213	Led-Blue	Blue LED	LEDB-000013	t
214	Led-Blue	Blue LED	LEDB-000014	t
215	Led-Blue	Blue LED	LEDB-000015	t
216	Led-Blue	Blue LED	LEDB-000016	t
217	Led-Blue	Blue LED	LEDB-000017	t
218	Led-Blue	Blue LED	LEDB-000018	t
219	Led-Blue	Blue LED	LEDB-000019	t
220	Led-Blue	Blue LED	LEDB-000020	t
221	Led-Blue	Blue LED	LEDB-000021	t
222	Led-Blue	Blue LED	LEDB-000022	t
223	Led-Blue	Blue LED	LEDB-000023	t
224	Led-Blue	Blue LED	LEDB-000024	t
225	Led-Blue	Blue LED	LEDB-000025	t
226	Led-Blue	Blue LED	LEDB-000026	t
227	Led-Blue	Blue LED	LEDB-000027	t
228	Led-Blue	Blue LED	LEDB-000028	t
229	Led-Blue	Blue LED	LEDB-000029	t
230	Led-Blue	Blue LED	LEDB-000030	t
231	Led-Blue	Blue LED	LEDB-000031	t
232	Led-Blue	Blue LED	LEDB-000032	t
233	Led-Blue	Blue LED	LEDB-000033	t
234	Led-Blue	Blue LED	LEDB-000034	t
235	Led-Blue	Blue LED	LEDB-000035	t
236	Led-Blue	Blue LED	LEDB-000036	t
237	Led-Blue	Blue LED	LEDB-000037	t
238	Led-Blue	Blue LED	LEDB-000038	t
239	Led-Blue	Blue LED	LEDB-000039	t
240	Led-Blue	Blue LED	LEDB-000040	t
241	Led-Blue	Blue LED	LEDB-000041	t
242	Led-Blue	Blue LED	LEDB-000042	t
243	Led-Blue	Blue LED	LEDB-000043	t
244	Led-Blue	Blue LED	LEDB-000044	t
245	Led-Blue	Blue LED	LEDB-000045	t
246	Led-Blue	Blue LED	LEDB-000046	t
247	Led-Blue	Blue LED	LEDB-000047	t
248	Led-Blue	Blue LED	LEDB-000048	t
249	Led-Blue	Blue LED	LEDB-000049	t
250	Led-Blue	Blue LED	LEDB-000050	t
251	Led-Blue	Blue LED	LEDB-000051	t
252	Led-Blue	Blue LED	LEDB-000052	t
253	Led-Blue	Blue LED	LEDB-000053	t
254	Led-Blue	Blue LED	LEDB-000054	t
255	Led-Blue	Blue LED	LEDB-000055	t
256	Led-Blue	Blue LED	LEDB-000056	t
257	Led-Blue	Blue LED	LEDB-000057	t
258	Led-Blue	Blue LED	LEDB-000058	t
259	Led-Blue	Blue LED	LEDB-000059	t
260	Led-Blue	Blue LED	LEDB-000060	t
261	Led-Blue	Blue LED	LEDB-000061	t
262	Led-Blue	Blue LED	LEDB-000062	t
263	Led-Blue	Blue LED	LEDB-000063	t
264	Led-Blue	Blue LED	LEDB-000064	t
265	Led-Blue	Blue LED	LEDB-000065	t
266	Led-Blue	Blue LED	LEDB-000066	t
267	Led-Blue	Blue LED	LEDB-000067	t
268	Led-Blue	Blue LED	LEDB-000068	t
269	Led-Blue	Blue LED	LEDB-000069	t
270	Led-Blue	Blue LED	LEDB-000070	t
271	Led-Blue	Blue LED	LEDB-000071	t
272	Led-Blue	Blue LED	LEDB-000072	t
273	Led-Blue	Blue LED	LEDB-000073	t
274	Led-Blue	Blue LED	LEDB-000074	t
275	Led-Blue	Blue LED	LEDB-000075	t
276	Led-Blue	Blue LED	LEDB-000076	t
277	Led-Blue	Blue LED	LEDB-000077	t
278	Led-Blue	Blue LED	LEDB-000078	t
279	Led-Blue	Blue LED	LEDB-000079	t
280	Led-Blue	Blue LED	LEDB-000080	t
281	Led-Blue	Blue LED	LEDB-000081	t
282	Led-Blue	Blue LED	LEDB-000082	t
283	Led-Blue	Blue LED	LEDB-000083	t
284	Led-Blue	Blue LED	LEDB-000084	t
285	Led-Blue	Blue LED	LEDB-000085	t
286	Led-Blue	Blue LED	LEDB-000086	t
287	Led-Blue	Blue LED	LEDB-000087	t
288	Led-Blue	Blue LED	LEDB-000088	t
289	Led-Blue	Blue LED	LEDB-000089	t
290	Led-Blue	Blue LED	LEDB-000090	t
291	Led-Blue	Blue LED	LEDB-000091	t
292	Led-Blue	Blue LED	LEDB-000092	t
293	Led-Blue	Blue LED	LEDB-000093	t
294	Led-Blue	Blue LED	LEDB-000094	t
295	Led-Blue	Blue LED	LEDB-000095	t
296	Led-Blue	Blue LED	LEDB-000096	t
297	Led-Blue	Blue LED	LEDB-000097	t
298	Led-Blue	Blue LED	LEDB-000098	t
299	Led-Blue	Blue LED	LEDB-000099	t
300	Led-Blue	Blue LED	LEDB-000100	t
301	Led-Yellow	Yellow LED	LEDY-000001	t
302	Led-Yellow	Yellow LED	LEDY-000002	t
303	Led-Yellow	Yellow LED	LEDY-000003	t
304	Led-Yellow	Yellow LED	LEDY-000004	t
305	Led-Yellow	Yellow LED	LEDY-000005	t
306	Led-Yellow	Yellow LED	LEDY-000006	t
307	Led-Yellow	Yellow LED	LEDY-000007	t
308	Led-Yellow	Yellow LED	LEDY-000008	t
309	Led-Yellow	Yellow LED	LEDY-000009	t
310	Led-Yellow	Yellow LED	LEDY-000010	t
311	Led-Yellow	Yellow LED	LEDY-000011	t
312	Led-Yellow	Yellow LED	LEDY-000012	t
313	Led-Yellow	Yellow LED	LEDY-000013	t
314	Led-Yellow	Yellow LED	LEDY-000014	t
315	Led-Yellow	Yellow LED	LEDY-000015	t
316	Led-Yellow	Yellow LED	LEDY-000016	t
317	Led-Yellow	Yellow LED	LEDY-000017	t
318	Led-Yellow	Yellow LED	LEDY-000018	t
319	Led-Yellow	Yellow LED	LEDY-000019	t
320	Led-Yellow	Yellow LED	LEDY-000020	t
321	Led-Yellow	Yellow LED	LEDY-000021	t
322	Led-Yellow	Yellow LED	LEDY-000022	t
323	Led-Yellow	Yellow LED	LEDY-000023	t
324	Led-Yellow	Yellow LED	LEDY-000024	t
325	Led-Yellow	Yellow LED	LEDY-000025	t
326	Led-Yellow	Yellow LED	LEDY-000026	t
327	Led-Yellow	Yellow LED	LEDY-000027	t
328	Led-Yellow	Yellow LED	LEDY-000028	t
329	Led-Yellow	Yellow LED	LEDY-000029	t
330	Led-Yellow	Yellow LED	LEDY-000030	t
331	Led-Yellow	Yellow LED	LEDY-000031	t
332	Led-Yellow	Yellow LED	LEDY-000032	t
333	Led-Yellow	Yellow LED	LEDY-000033	t
334	Led-Yellow	Yellow LED	LEDY-000034	t
335	Led-Yellow	Yellow LED	LEDY-000035	t
336	Led-Yellow	Yellow LED	LEDY-000036	t
337	Led-Yellow	Yellow LED	LEDY-000037	t
338	Led-Yellow	Yellow LED	LEDY-000038	t
339	Led-Yellow	Yellow LED	LEDY-000039	t
340	Led-Yellow	Yellow LED	LEDY-000040	t
341	Led-Yellow	Yellow LED	LEDY-000041	t
342	Led-Yellow	Yellow LED	LEDY-000042	t
343	Led-Yellow	Yellow LED	LEDY-000043	t
344	Led-Yellow	Yellow LED	LEDY-000044	t
345	Led-Yellow	Yellow LED	LEDY-000045	t
346	Led-Yellow	Yellow LED	LEDY-000046	t
347	Led-Yellow	Yellow LED	LEDY-000047	t
348	Led-Yellow	Yellow LED	LEDY-000048	t
349	Led-Yellow	Yellow LED	LEDY-000049	t
350	Led-Yellow	Yellow LED	LEDY-000050	t
351	Led-Yellow	Yellow LED	LEDY-000051	t
352	Led-Yellow	Yellow LED	LEDY-000052	t
353	Led-Yellow	Yellow LED	LEDY-000053	t
354	Led-Yellow	Yellow LED	LEDY-000054	t
355	Led-Yellow	Yellow LED	LEDY-000055	t
356	Led-Yellow	Yellow LED	LEDY-000056	t
357	Led-Yellow	Yellow LED	LEDY-000057	t
358	Led-Yellow	Yellow LED	LEDY-000058	t
359	Led-Yellow	Yellow LED	LEDY-000059	t
360	Led-Yellow	Yellow LED	LEDY-000060	t
361	Led-Yellow	Yellow LED	LEDY-000061	t
362	Led-Yellow	Yellow LED	LEDY-000062	t
363	Led-Yellow	Yellow LED	LEDY-000063	t
364	Led-Yellow	Yellow LED	LEDY-000064	t
365	Led-Yellow	Yellow LED	LEDY-000065	t
366	Led-Yellow	Yellow LED	LEDY-000066	t
367	Led-Yellow	Yellow LED	LEDY-000067	t
368	Led-Yellow	Yellow LED	LEDY-000068	t
369	Led-Yellow	Yellow LED	LEDY-000069	t
370	Led-Yellow	Yellow LED	LEDY-000070	t
371	Led-Yellow	Yellow LED	LEDY-000071	t
372	Led-Yellow	Yellow LED	LEDY-000072	t
373	Led-Yellow	Yellow LED	LEDY-000073	t
374	Led-Yellow	Yellow LED	LEDY-000074	t
375	Led-Yellow	Yellow LED	LEDY-000075	t
376	Led-Yellow	Yellow LED	LEDY-000076	t
377	Led-Yellow	Yellow LED	LEDY-000077	t
378	Led-Yellow	Yellow LED	LEDY-000078	t
379	Led-Yellow	Yellow LED	LEDY-000079	t
380	Led-Yellow	Yellow LED	LEDY-000080	t
381	Led-Yellow	Yellow LED	LEDY-000081	t
382	Led-Yellow	Yellow LED	LEDY-000082	t
383	Led-Yellow	Yellow LED	LEDY-000083	t
384	Led-Yellow	Yellow LED	LEDY-000084	t
385	Led-Yellow	Yellow LED	LEDY-000085	t
386	Led-Yellow	Yellow LED	LEDY-000086	t
387	Led-Yellow	Yellow LED	LEDY-000087	t
388	Led-Yellow	Yellow LED	LEDY-000088	t
389	Led-Yellow	Yellow LED	LEDY-000089	t
390	Led-Yellow	Yellow LED	LEDY-000090	t
391	Led-Yellow	Yellow LED	LEDY-000091	t
392	Led-Yellow	Yellow LED	LEDY-000092	t
393	Led-Yellow	Yellow LED	LEDY-000093	t
394	Led-Yellow	Yellow LED	LEDY-000094	t
395	Led-Yellow	Yellow LED	LEDY-000095	t
396	Led-Yellow	Yellow LED	LEDY-000096	t
397	Led-Yellow	Yellow LED	LEDY-000097	t
398	Led-Yellow	Yellow LED	LEDY-000098	t
399	Led-Yellow	Yellow LED	LEDY-000099	t
400	Led-Yellow	Yellow LED	LEDY-000100	t
401	RFID	RFID Reader	RFID-000001	t
402	RFID	RFID Reader	RFID-000002	t
403	RFID	RFID Reader	RFID-000003	t
404	RFID	RFID Reader	RFID-000004	t
405	RFID	RFID Reader	RFID-000005	t
406	RFID	RFID Reader	RFID-000006	t
407	RFID	RFID Reader	RFID-000007	t
408	RFID	RFID Reader	RFID-000008	t
409	RFID	RFID Reader	RFID-000009	t
410	RFID	RFID Reader	RFID-000010	t
411	RFID	RFID Reader	RFID-000011	t
412	RFID	RFID Reader	RFID-000012	t
413	RFID	RFID Reader	RFID-000013	t
414	RFID	RFID Reader	RFID-000014	t
415	RFID	RFID Reader	RFID-000015	t
416	RFID	RFID Reader	RFID-000016	t
417	RFID	RFID Reader	RFID-000017	t
418	RFID	RFID Reader	RFID-000018	t
419	RFID	RFID Reader	RFID-000019	t
420	RFID	RFID Reader	RFID-000020	t
421	RFID	RFID Reader	RFID-000021	t
422	RFID	RFID Reader	RFID-000022	t
423	RFID	RFID Reader	RFID-000023	t
424	RFID	RFID Reader	RFID-000024	t
425	RFID	RFID Reader	RFID-000025	t
426	RFID	RFID Reader	RFID-000026	t
427	RFID	RFID Reader	RFID-000027	t
428	RFID	RFID Reader	RFID-000028	t
429	RFID	RFID Reader	RFID-000029	t
430	RFID	RFID Reader	RFID-000030	t
431	RFID	RFID Reader	RFID-000031	t
432	RFID	RFID Reader	RFID-000032	t
433	RFID	RFID Reader	RFID-000033	t
434	RFID	RFID Reader	RFID-000034	t
435	RFID	RFID Reader	RFID-000035	t
436	RFID	RFID Reader	RFID-000036	t
437	RFID	RFID Reader	RFID-000037	t
438	RFID	RFID Reader	RFID-000038	t
439	RFID	RFID Reader	RFID-000039	t
440	RFID	RFID Reader	RFID-000040	t
441	RFID	RFID Reader	RFID-000041	t
442	RFID	RFID Reader	RFID-000042	t
443	RFID	RFID Reader	RFID-000043	t
444	RFID	RFID Reader	RFID-000044	t
445	RFID	RFID Reader	RFID-000045	t
446	RFID	RFID Reader	RFID-000046	t
447	RFID	RFID Reader	RFID-000047	t
448	RFID	RFID Reader	RFID-000048	t
449	RFID	RFID Reader	RFID-000049	t
450	RFID	RFID Reader	RFID-000050	t
451	RFID	RFID Reader	RFID-000051	t
452	RFID	RFID Reader	RFID-000052	t
453	RFID	RFID Reader	RFID-000053	t
454	RFID	RFID Reader	RFID-000054	t
455	RFID	RFID Reader	RFID-000055	t
456	RFID	RFID Reader	RFID-000056	t
457	RFID	RFID Reader	RFID-000057	t
458	RFID	RFID Reader	RFID-000058	t
459	RFID	RFID Reader	RFID-000059	t
460	RFID	RFID Reader	RFID-000060	t
461	RFID	RFID Reader	RFID-000061	t
462	RFID	RFID Reader	RFID-000062	t
463	RFID	RFID Reader	RFID-000063	t
464	RFID	RFID Reader	RFID-000064	t
465	RFID	RFID Reader	RFID-000065	t
466	RFID	RFID Reader	RFID-000066	t
467	RFID	RFID Reader	RFID-000067	t
468	RFID	RFID Reader	RFID-000068	t
469	RFID	RFID Reader	RFID-000069	t
470	RFID	RFID Reader	RFID-000070	t
471	RFID	RFID Reader	RFID-000071	t
472	RFID	RFID Reader	RFID-000072	t
473	RFID	RFID Reader	RFID-000073	t
474	RFID	RFID Reader	RFID-000074	t
475	RFID	RFID Reader	RFID-000075	t
476	RFID	RFID Reader	RFID-000076	t
477	RFID	RFID Reader	RFID-000077	t
478	RFID	RFID Reader	RFID-000078	t
479	RFID	RFID Reader	RFID-000079	t
480	RFID	RFID Reader	RFID-000080	t
481	RFID	RFID Reader	RFID-000081	t
482	RFID	RFID Reader	RFID-000082	t
483	RFID	RFID Reader	RFID-000083	t
484	RFID	RFID Reader	RFID-000084	t
485	RFID	RFID Reader	RFID-000085	t
486	RFID	RFID Reader	RFID-000086	t
487	RFID	RFID Reader	RFID-000087	t
488	RFID	RFID Reader	RFID-000088	t
489	RFID	RFID Reader	RFID-000089	t
490	RFID	RFID Reader	RFID-000090	t
491	RFID	RFID Reader	RFID-000091	t
492	RFID	RFID Reader	RFID-000092	t
493	RFID	RFID Reader	RFID-000093	t
494	RFID	RFID Reader	RFID-000094	t
495	RFID	RFID Reader	RFID-000095	t
496	RFID	RFID Reader	RFID-000096	t
497	RFID	RFID Reader	RFID-000097	t
498	RFID	RFID Reader	RFID-000098	t
499	RFID	RFID Reader	RFID-000099	t
500	RFID	RFID Reader	RFID-000100	t
501	SERVO	Servo Motor	SERVO-000001	t
502	SERVO	Servo Motor	SERVO-000002	t
503	SERVO	Servo Motor	SERVO-000003	t
504	SERVO	Servo Motor	SERVO-000004	t
505	SERVO	Servo Motor	SERVO-000005	t
506	SERVO	Servo Motor	SERVO-000006	t
507	SERVO	Servo Motor	SERVO-000007	t
508	SERVO	Servo Motor	SERVO-000008	t
509	SERVO	Servo Motor	SERVO-000009	t
510	SERVO	Servo Motor	SERVO-000010	t
511	SERVO	Servo Motor	SERVO-000011	t
512	SERVO	Servo Motor	SERVO-000012	t
513	SERVO	Servo Motor	SERVO-000013	t
514	SERVO	Servo Motor	SERVO-000014	t
515	SERVO	Servo Motor	SERVO-000015	t
516	SERVO	Servo Motor	SERVO-000016	t
517	SERVO	Servo Motor	SERVO-000017	t
518	SERVO	Servo Motor	SERVO-000018	t
519	SERVO	Servo Motor	SERVO-000019	t
520	SERVO	Servo Motor	SERVO-000020	t
521	SERVO	Servo Motor	SERVO-000021	t
522	SERVO	Servo Motor	SERVO-000022	t
523	SERVO	Servo Motor	SERVO-000023	t
524	SERVO	Servo Motor	SERVO-000024	t
525	SERVO	Servo Motor	SERVO-000025	t
526	SERVO	Servo Motor	SERVO-000026	t
527	SERVO	Servo Motor	SERVO-000027	t
528	SERVO	Servo Motor	SERVO-000028	t
529	SERVO	Servo Motor	SERVO-000029	t
530	SERVO	Servo Motor	SERVO-000030	t
531	SERVO	Servo Motor	SERVO-000031	t
532	SERVO	Servo Motor	SERVO-000032	t
533	SERVO	Servo Motor	SERVO-000033	t
534	SERVO	Servo Motor	SERVO-000034	t
535	SERVO	Servo Motor	SERVO-000035	t
536	SERVO	Servo Motor	SERVO-000036	t
537	SERVO	Servo Motor	SERVO-000037	t
538	SERVO	Servo Motor	SERVO-000038	t
539	SERVO	Servo Motor	SERVO-000039	t
540	SERVO	Servo Motor	SERVO-000040	t
541	SERVO	Servo Motor	SERVO-000041	t
542	SERVO	Servo Motor	SERVO-000042	t
543	SERVO	Servo Motor	SERVO-000043	t
544	SERVO	Servo Motor	SERVO-000044	t
545	SERVO	Servo Motor	SERVO-000045	t
546	SERVO	Servo Motor	SERVO-000046	t
547	SERVO	Servo Motor	SERVO-000047	t
548	SERVO	Servo Motor	SERVO-000048	t
549	SERVO	Servo Motor	SERVO-000049	t
550	SERVO	Servo Motor	SERVO-000050	t
551	SERVO	Servo Motor	SERVO-000051	t
552	SERVO	Servo Motor	SERVO-000052	t
553	SERVO	Servo Motor	SERVO-000053	t
554	SERVO	Servo Motor	SERVO-000054	t
555	SERVO	Servo Motor	SERVO-000055	t
556	SERVO	Servo Motor	SERVO-000056	t
557	SERVO	Servo Motor	SERVO-000057	t
558	SERVO	Servo Motor	SERVO-000058	t
559	SERVO	Servo Motor	SERVO-000059	t
560	SERVO	Servo Motor	SERVO-000060	t
561	SERVO	Servo Motor	SERVO-000061	t
562	SERVO	Servo Motor	SERVO-000062	t
563	SERVO	Servo Motor	SERVO-000063	t
564	SERVO	Servo Motor	SERVO-000064	t
565	SERVO	Servo Motor	SERVO-000065	t
566	SERVO	Servo Motor	SERVO-000066	t
567	SERVO	Servo Motor	SERVO-000067	t
568	SERVO	Servo Motor	SERVO-000068	t
569	SERVO	Servo Motor	SERVO-000069	t
570	SERVO	Servo Motor	SERVO-000070	t
571	SERVO	Servo Motor	SERVO-000071	t
572	SERVO	Servo Motor	SERVO-000072	t
573	SERVO	Servo Motor	SERVO-000073	t
574	SERVO	Servo Motor	SERVO-000074	t
575	SERVO	Servo Motor	SERVO-000075	t
576	SERVO	Servo Motor	SERVO-000076	t
577	SERVO	Servo Motor	SERVO-000077	t
578	SERVO	Servo Motor	SERVO-000078	t
579	SERVO	Servo Motor	SERVO-000079	t
580	SERVO	Servo Motor	SERVO-000080	t
581	SERVO	Servo Motor	SERVO-000081	t
582	SERVO	Servo Motor	SERVO-000082	t
583	SERVO	Servo Motor	SERVO-000083	t
584	SERVO	Servo Motor	SERVO-000084	t
585	SERVO	Servo Motor	SERVO-000085	t
586	SERVO	Servo Motor	SERVO-000086	t
587	SERVO	Servo Motor	SERVO-000087	t
588	SERVO	Servo Motor	SERVO-000088	t
589	SERVO	Servo Motor	SERVO-000089	t
590	SERVO	Servo Motor	SERVO-000090	t
591	SERVO	Servo Motor	SERVO-000091	t
592	SERVO	Servo Motor	SERVO-000092	t
593	SERVO	Servo Motor	SERVO-000093	t
594	SERVO	Servo Motor	SERVO-000094	t
595	SERVO	Servo Motor	SERVO-000095	t
596	SERVO	Servo Motor	SERVO-000096	t
597	SERVO	Servo Motor	SERVO-000097	t
598	SERVO	Servo Motor	SERVO-000098	t
599	SERVO	Servo Motor	SERVO-000099	t
600	SERVO	Servo Motor	SERVO-000100	t
601	BUZZER	Buzzer	BUZ-000001	t
602	BUZZER	Buzzer	BUZ-000002	t
603	BUZZER	Buzzer	BUZ-000003	t
604	BUZZER	Buzzer	BUZ-000004	t
605	BUZZER	Buzzer	BUZ-000005	t
606	BUZZER	Buzzer	BUZ-000006	t
607	BUZZER	Buzzer	BUZ-000007	t
608	BUZZER	Buzzer	BUZ-000008	t
609	BUZZER	Buzzer	BUZ-000009	t
610	BUZZER	Buzzer	BUZ-000010	t
611	BUZZER	Buzzer	BUZ-000011	t
612	BUZZER	Buzzer	BUZ-000012	t
613	BUZZER	Buzzer	BUZ-000013	t
614	BUZZER	Buzzer	BUZ-000014	t
615	BUZZER	Buzzer	BUZ-000015	t
616	BUZZER	Buzzer	BUZ-000016	t
617	BUZZER	Buzzer	BUZ-000017	t
618	BUZZER	Buzzer	BUZ-000018	t
619	BUZZER	Buzzer	BUZ-000019	t
620	BUZZER	Buzzer	BUZ-000020	t
621	BUZZER	Buzzer	BUZ-000021	t
622	BUZZER	Buzzer	BUZ-000022	t
623	BUZZER	Buzzer	BUZ-000023	t
624	BUZZER	Buzzer	BUZ-000024	t
625	BUZZER	Buzzer	BUZ-000025	t
626	BUZZER	Buzzer	BUZ-000026	t
627	BUZZER	Buzzer	BUZ-000027	t
628	BUZZER	Buzzer	BUZ-000028	t
629	BUZZER	Buzzer	BUZ-000029	t
630	BUZZER	Buzzer	BUZ-000030	t
631	BUZZER	Buzzer	BUZ-000031	t
632	BUZZER	Buzzer	BUZ-000032	t
633	BUZZER	Buzzer	BUZ-000033	t
634	BUZZER	Buzzer	BUZ-000034	t
635	BUZZER	Buzzer	BUZ-000035	t
636	BUZZER	Buzzer	BUZ-000036	t
637	BUZZER	Buzzer	BUZ-000037	t
638	BUZZER	Buzzer	BUZ-000038	t
639	BUZZER	Buzzer	BUZ-000039	t
640	BUZZER	Buzzer	BUZ-000040	t
641	BUZZER	Buzzer	BUZ-000041	t
642	BUZZER	Buzzer	BUZ-000042	t
643	BUZZER	Buzzer	BUZ-000043	t
644	BUZZER	Buzzer	BUZ-000044	t
645	BUZZER	Buzzer	BUZ-000045	t
646	BUZZER	Buzzer	BUZ-000046	t
647	BUZZER	Buzzer	BUZ-000047	t
648	BUZZER	Buzzer	BUZ-000048	t
649	BUZZER	Buzzer	BUZ-000049	t
650	BUZZER	Buzzer	BUZ-000050	t
651	BUZZER	Buzzer	BUZ-000051	t
652	BUZZER	Buzzer	BUZ-000052	t
653	BUZZER	Buzzer	BUZ-000053	t
654	BUZZER	Buzzer	BUZ-000054	t
655	BUZZER	Buzzer	BUZ-000055	t
656	BUZZER	Buzzer	BUZ-000056	t
657	BUZZER	Buzzer	BUZ-000057	t
658	BUZZER	Buzzer	BUZ-000058	t
659	BUZZER	Buzzer	BUZ-000059	t
660	BUZZER	Buzzer	BUZ-000060	t
661	BUZZER	Buzzer	BUZ-000061	t
662	BUZZER	Buzzer	BUZ-000062	t
663	BUZZER	Buzzer	BUZ-000063	t
664	BUZZER	Buzzer	BUZ-000064	t
665	BUZZER	Buzzer	BUZ-000065	t
666	BUZZER	Buzzer	BUZ-000066	t
667	BUZZER	Buzzer	BUZ-000067	t
668	BUZZER	Buzzer	BUZ-000068	t
669	BUZZER	Buzzer	BUZ-000069	t
670	BUZZER	Buzzer	BUZ-000070	t
671	BUZZER	Buzzer	BUZ-000071	t
672	BUZZER	Buzzer	BUZ-000072	t
673	BUZZER	Buzzer	BUZ-000073	t
674	BUZZER	Buzzer	BUZ-000074	t
675	BUZZER	Buzzer	BUZ-000075	t
676	BUZZER	Buzzer	BUZ-000076	t
677	BUZZER	Buzzer	BUZ-000077	t
678	BUZZER	Buzzer	BUZ-000078	t
679	BUZZER	Buzzer	BUZ-000079	t
680	BUZZER	Buzzer	BUZ-000080	t
681	BUZZER	Buzzer	BUZ-000081	t
682	BUZZER	Buzzer	BUZ-000082	t
683	BUZZER	Buzzer	BUZ-000083	t
684	BUZZER	Buzzer	BUZ-000084	t
685	BUZZER	Buzzer	BUZ-000085	t
686	BUZZER	Buzzer	BUZ-000086	t
687	BUZZER	Buzzer	BUZ-000087	t
688	BUZZER	Buzzer	BUZ-000088	t
689	BUZZER	Buzzer	BUZ-000089	t
690	BUZZER	Buzzer	BUZ-000090	t
691	BUZZER	Buzzer	BUZ-000091	t
692	BUZZER	Buzzer	BUZ-000092	t
693	BUZZER	Buzzer	BUZ-000093	t
694	BUZZER	Buzzer	BUZ-000094	t
695	BUZZER	Buzzer	BUZ-000095	t
696	BUZZER	Buzzer	BUZ-000096	t
697	BUZZER	Buzzer	BUZ-000097	t
698	BUZZER	Buzzer	BUZ-000098	t
699	BUZZER	Buzzer	BUZ-000099	t
700	BUZZER	Buzzer	BUZ-000100	t
701	DHT11	Temp & Humidity	DHT11-000001	t
702	DHT11	Temp & Humidity	DHT11-000002	t
703	DHT11	Temp & Humidity	DHT11-000003	t
704	DHT11	Temp & Humidity	DHT11-000004	t
705	DHT11	Temp & Humidity	DHT11-000005	t
706	DHT11	Temp & Humidity	DHT11-000006	t
707	DHT11	Temp & Humidity	DHT11-000007	t
708	DHT11	Temp & Humidity	DHT11-000008	t
709	DHT11	Temp & Humidity	DHT11-000009	t
710	DHT11	Temp & Humidity	DHT11-000010	t
711	DHT11	Temp & Humidity	DHT11-000011	t
712	DHT11	Temp & Humidity	DHT11-000012	t
713	DHT11	Temp & Humidity	DHT11-000013	t
714	DHT11	Temp & Humidity	DHT11-000014	t
715	DHT11	Temp & Humidity	DHT11-000015	t
716	DHT11	Temp & Humidity	DHT11-000016	t
717	DHT11	Temp & Humidity	DHT11-000017	t
718	DHT11	Temp & Humidity	DHT11-000018	t
719	DHT11	Temp & Humidity	DHT11-000019	t
720	DHT11	Temp & Humidity	DHT11-000020	t
721	DHT11	Temp & Humidity	DHT11-000021	t
722	DHT11	Temp & Humidity	DHT11-000022	t
723	DHT11	Temp & Humidity	DHT11-000023	t
724	DHT11	Temp & Humidity	DHT11-000024	t
725	DHT11	Temp & Humidity	DHT11-000025	t
726	DHT11	Temp & Humidity	DHT11-000026	t
727	DHT11	Temp & Humidity	DHT11-000027	t
728	DHT11	Temp & Humidity	DHT11-000028	t
729	DHT11	Temp & Humidity	DHT11-000029	t
730	DHT11	Temp & Humidity	DHT11-000030	t
731	DHT11	Temp & Humidity	DHT11-000031	t
732	DHT11	Temp & Humidity	DHT11-000032	t
733	DHT11	Temp & Humidity	DHT11-000033	t
734	DHT11	Temp & Humidity	DHT11-000034	t
735	DHT11	Temp & Humidity	DHT11-000035	t
736	DHT11	Temp & Humidity	DHT11-000036	t
737	DHT11	Temp & Humidity	DHT11-000037	t
738	DHT11	Temp & Humidity	DHT11-000038	t
739	DHT11	Temp & Humidity	DHT11-000039	t
740	DHT11	Temp & Humidity	DHT11-000040	t
741	DHT11	Temp & Humidity	DHT11-000041	t
742	DHT11	Temp & Humidity	DHT11-000042	t
743	DHT11	Temp & Humidity	DHT11-000043	t
744	DHT11	Temp & Humidity	DHT11-000044	t
745	DHT11	Temp & Humidity	DHT11-000045	t
746	DHT11	Temp & Humidity	DHT11-000046	t
747	DHT11	Temp & Humidity	DHT11-000047	t
748	DHT11	Temp & Humidity	DHT11-000048	t
749	DHT11	Temp & Humidity	DHT11-000049	t
750	DHT11	Temp & Humidity	DHT11-000050	t
751	DHT11	Temp & Humidity	DHT11-000051	t
752	DHT11	Temp & Humidity	DHT11-000052	t
753	DHT11	Temp & Humidity	DHT11-000053	t
754	DHT11	Temp & Humidity	DHT11-000054	t
755	DHT11	Temp & Humidity	DHT11-000055	t
756	DHT11	Temp & Humidity	DHT11-000056	t
757	DHT11	Temp & Humidity	DHT11-000057	t
758	DHT11	Temp & Humidity	DHT11-000058	t
759	DHT11	Temp & Humidity	DHT11-000059	t
760	DHT11	Temp & Humidity	DHT11-000060	t
761	DHT11	Temp & Humidity	DHT11-000061	t
762	DHT11	Temp & Humidity	DHT11-000062	t
763	DHT11	Temp & Humidity	DHT11-000063	t
764	DHT11	Temp & Humidity	DHT11-000064	t
765	DHT11	Temp & Humidity	DHT11-000065	t
766	DHT11	Temp & Humidity	DHT11-000066	t
767	DHT11	Temp & Humidity	DHT11-000067	t
768	DHT11	Temp & Humidity	DHT11-000068	t
769	DHT11	Temp & Humidity	DHT11-000069	t
770	DHT11	Temp & Humidity	DHT11-000070	t
771	DHT11	Temp & Humidity	DHT11-000071	t
772	DHT11	Temp & Humidity	DHT11-000072	t
773	DHT11	Temp & Humidity	DHT11-000073	t
774	DHT11	Temp & Humidity	DHT11-000074	t
775	DHT11	Temp & Humidity	DHT11-000075	t
776	DHT11	Temp & Humidity	DHT11-000076	t
777	DHT11	Temp & Humidity	DHT11-000077	t
778	DHT11	Temp & Humidity	DHT11-000078	t
779	DHT11	Temp & Humidity	DHT11-000079	t
780	DHT11	Temp & Humidity	DHT11-000080	t
781	DHT11	Temp & Humidity	DHT11-000081	t
782	DHT11	Temp & Humidity	DHT11-000082	t
783	DHT11	Temp & Humidity	DHT11-000083	t
784	DHT11	Temp & Humidity	DHT11-000084	t
785	DHT11	Temp & Humidity	DHT11-000085	t
786	DHT11	Temp & Humidity	DHT11-000086	t
787	DHT11	Temp & Humidity	DHT11-000087	t
788	DHT11	Temp & Humidity	DHT11-000088	t
789	DHT11	Temp & Humidity	DHT11-000089	t
790	DHT11	Temp & Humidity	DHT11-000090	t
791	DHT11	Temp & Humidity	DHT11-000091	t
792	DHT11	Temp & Humidity	DHT11-000092	t
793	DHT11	Temp & Humidity	DHT11-000093	t
794	DHT11	Temp & Humidity	DHT11-000094	t
795	DHT11	Temp & Humidity	DHT11-000095	t
796	DHT11	Temp & Humidity	DHT11-000096	t
797	DHT11	Temp & Humidity	DHT11-000097	t
798	DHT11	Temp & Humidity	DHT11-000098	t
799	DHT11	Temp & Humidity	DHT11-000099	t
800	DHT11	Temp & Humidity	DHT11-000100	t
801	RFID	RFID Reader	RFID-001	t
802	LED-White	White LED	LED-001	t
803	LED-Red	Red LED	LED-002	t
804	LED-Blue	Blue LED	LED-003	t
805	LED-Yellow	Yellow LED	LED-004	t
806	BUZZER	Buzzer	BUZ-001	t
807	SERVO-1	Servo Motor 1	SERVO-001	t
808	SERVO-2	Servo Motor 2	SERVO-002	t
809	DHT11	Temp & Humidity	DHT11-001	t
\.


--
-- TOC entry 3374 (class 0 OID 16568)
-- Dependencies: 220
-- Data for Name: user_devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_devices (id, assigned_name, device_id, user_id, active, user_room_id, status) FROM stdin;
5	Mutfak Lamba	2	1	t	12	ACTIVE
6	Mutfak Lambası	3	9	t	28	ACTIVE
8	Ofis 1 Sıcaklık & Nem	701	9	t	30	ACTIVE
9	Ofis Kapı	502	1	t	19	ACTIVE
4	Salon Lambası	1	1	t	11	ACTIVE
11	Oturma Odası Lambası	5	9	f	29	RETIRED
12	Oturma Odası Lambası	6	9	f	29	INACTIVE_RESERVED
10	Oturma Odası Lambası	4	1	t	41	ACTIVE
13	Ofis Kapısı	503	1	t	19	ACTIVE
7	Ofis Kapısı	501	9	t	30	ACTIVE
14	Ofis 1 Lamba	101	7	t	32	ACTIVE
15	Salon Sarı Lamba	301	8	t	27	ACTIVE
16	Ofis 1 Mavi Lamba	201	9	t	30	ACTIVE
2	Banyo Alarm	601	1	t	16	ACTIVE
17	Ofis 2 Kartı	401	7	t	42	ACTIVE
18	Ofis 2 Alarm	602	7	t	42	ACTIVE
19	Ofis 1 Alarm	603	7	t	32	ACTIVE
20	Ofis 1 ID:8 Kartı	402	8	t	43	ACTIVE
21	Salon Lambası Beyaz	7	1	t	11	ACTIVE
22	Koridor Alarm	604	1	t	22	ACTIVE
\.


--
-- TOC entry 3376 (class 0 OID 16653)
-- Dependencies: 222
-- Data for Name: user_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_room (id, user_id, room_name, active) FROM stdin;
11	1	Salon	t
12	1	Mutfak	t
13	1	Yatak Odası 1	t
14	1	Yatak Odası 2	t
15	1	Yatak Odası 3	t
16	1	Banyo	t
17	1	Çocuk Odası	t
18	1	Misafir Odası	t
19	1	Ofis 1	t
20	1	Ofis 2	t
21	1	Ofis 3	t
22	1	Koridor	t
23	1	Ofis 4	t
24	6	Salon	f
25	6	Fabrika 1	f
26	6	Fabrika 2	f
27	8	Salon	t
28	9	Mutfak	t
29	9	Oturma Odası	t
30	9	Ofis 1	t
31	9	Ofis 2	t
32	7	Ofis 1	t
33	5	Oturma Odası	f
34	5	Yatak Odası	f
35	5	Banyo 1	f
36	5	Banyo 2	f
37	5	Mutfak	f
38	5	Salon	f
39	1	Yeşil ODA	t
40	1	Kırmızı Oda	t
41	1	Oturma Odası	t
42	7	Ofis 2	t
43	8	Ofis 1	t
44	1	Mustafa'nın Odası	t
\.


--
-- TOC entry 3370 (class 0 OID 16438)
-- Dependencies: 216
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, first_name, last_name, email, password, active) FROM stdin;
1	Mustafa	ÇETİN	mc.cetin.mustafa@gmail.com	Kek.1903	t
4	Abbas Can	YILDIZ	canylddz0@gmail.com	Abbas.1905	f
6	Sergen	YALÇIN	sergen.yalcin@gmail.com	Beşiktaş.1903	f
7	Samet	BARUĞ	samet.barug@gmail.com	Akgun.1903	t
8	Mikail	BARUĞ	mikail.barug@gmail.com	Akgun.1903	t
9	Eren	TAŞ	eren.tas@gmail.com	Akgun.1903	t
5	Abbas Can	YILDIZ	canylddz01@gmail.com	Abbas.1905	f
\.


--
-- TOC entry 3386 (class 0 OID 0)
-- Dependencies: 217
-- Name: devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.devices_id_seq', 809, true);


--
-- TOC entry 3387 (class 0 OID 0)
-- Dependencies: 219
-- Name: user_devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_devices_id_seq', 22, true);


--
-- TOC entry 3388 (class 0 OID 0)
-- Dependencies: 221
-- Name: user_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_room_id_seq', 44, true);


--
-- TOC entry 3389 (class 0 OID 0)
-- Dependencies: 215
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 9, true);


--
-- TOC entry 3209 (class 2606 OID 16455)
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- TOC entry 3211 (class 2606 OID 16465)
-- Name: devices ukjb0tk7mjqovv70vdodi1dycmm; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT ukjb0tk7mjqovv70vdodi1dycmm UNIQUE (device_uid);


--
-- TOC entry 3218 (class 2606 OID 16661)
-- Name: user_room uq_user_room; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_room
    ADD CONSTRAINT uq_user_room UNIQUE (user_id, room_name);


--
-- TOC entry 3214 (class 2606 OID 16574)
-- Name: user_devices user_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_pkey PRIMARY KEY (id);


--
-- TOC entry 3220 (class 2606 OID 16659)
-- Name: user_room user_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_room
    ADD CONSTRAINT user_room_pkey PRIMARY KEY (id);


--
-- TOC entry 3205 (class 2606 OID 16463)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3207 (class 2606 OID 16445)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3216 (class 1259 OID 16667)
-- Name: idx_user_room_user_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_room_user_active ON public.user_room USING btree (user_id, active);


--
-- TOC entry 3212 (class 1259 OID 16683)
-- Name: ux_devices_uid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_devices_uid ON public.devices USING btree (device_uid);


--
-- TOC entry 3215 (class 1259 OID 16699)
-- Name: ux_user_devices_device_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_user_devices_device_unique ON public.user_devices USING btree (device_id);


--
-- TOC entry 3221 (class 2606 OID 16668)
-- Name: user_devices fk_user_devices_user_room; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT fk_user_devices_user_room FOREIGN KEY (user_room_id) REFERENCES public.user_room(id) ON DELETE SET NULL;


--
-- TOC entry 3222 (class 2606 OID 16575)
-- Name: user_devices user_devices_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id);


--
-- TOC entry 3223 (class 2606 OID 16580)
-- Name: user_devices user_devices_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3224 (class 2606 OID 16662)
-- Name: user_room user_room_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_room
    ADD CONSTRAINT user_room_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2025-08-18 14:22:53

--
-- PostgreSQL database dump complete
--

